#!/usr/bin/env python3

import re
from gradelib import *

r = Runner(save("xv6.out"))

@test(0, "pgtbltest")
def test_pgtbltest():
    r.run_qemu(shell_script([
        'pgtbltest'
    ]), timeout=300)

@test(35, "pgtbltest: ugetpid", parent=test_pgtbltest)
def test_ugetpid_():
    r.match('^ugetpid_test: OK$')

@test(20, "pgtbltest: print_kpgtbl", parent=test_pgtbltest)
def test_print_kpgtbl_():
    r.match(
        r'^page table 0x',
        r'^ \.\.0x0000000000000000',
        r'^ \.\. \.\.0x0000000000000000',
        r'^ \.\. \.\. \.\.0x0000000000000000',
        r'^ \.\. \.\. \.\.0x0000000000001000',
        r'^ \.\. \.\. \.\.0x0000000000002000',
        r'^ \.\. \.\. \.\.0x0000000000003000',
        r'^ \.\.(0xffffffffc0000000|0x0000003fc0000000)',
        r'^ \.\. \.\.(0xffffffffffe00000|0x0000003fffe00000)',
        r'^ \.\. \.\. \.\.(0xffffffffffffe000|0x0000003fffffe000)',
        r'^ \.\. \.\. \.\.(0xfffffffffffff000|0x0000003ffffff000)',
    )

@test(30, "pgtbltest: superpg", parent=test_pgtbltest)
def test_superpg_():
    r.match('^superpg_fork: OK$')
    r.match('^superpg_free: OK$')

@test(20, "answers-pgtbl.txt")
def test_answers():
    # just a simple sanity check, will be graded manually
    check_answers("answers-pgtbl.txt")

@test(0, "usertests")
def test_usertests():
    r.run_qemu(shell_script([
        'usertests -q'
    ]), timeout=300)

@test(5, "time")
def test_time():
    check_time()

run_tests()
